### ISSUE TITLE
Columns shifted in .csv output; mismatched columns & data

### ISSUE THREAD

**Issue by aklohr** [movestore/Daily-Rest-Sites#5]
Hi @andreakoelzsch , at the last workshop we noticed that the columns in the "data_rest_selectedTime.csv" output are shifted to the right one column, meaning many columns aren't labeled with the correct header. When opening the file in Excel, this appears to originate in the column "Geometry", which is split into two columns, creating an offset _(see screenshot below)_. Is a fix for this possible?
![image](https://github.com/user-attachments/assets/f09dc691-8325-4c98-948c-474cfdd8428d)

Also, it seems after the last update the first ~20 columns in the "data_rest_selectedTime.csv" output are accessory measurements, meaning the user has to scroll really far to the right to see timestamps, lat/long, etc. Is it possible to reorder the attributes so the "primary" ones (i.e.., individual_local_identifier, timestamp, lat/long) come first, or can that not be adjusted?

**Comment by andreakoelzsch** [comment]
done by removing "geometry", adding location.long and location.lat and bringing a set of "important" columns to the front.
